name: drag_select_grid_view_example
description: Demonstrates how to use the drag_select_grid_view package.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  drag_select_grid_view:
    path: ../

flutter:
  uses-material-design: true